### ISSUE TITLE
Chọn đề tài, đặt tên nhóm, chọn master scrum

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#1]
Đề tài:
Theo mình là nên chọn đề tài đơn giản vừa sức thôi như: làm trang quản lý khách sạn chẳng hạn.
Tên nhóm:
Có thể lấy chữ cái đầu của tên mỗi bạn trong nhóm để làm tên khách sạn hoặc tên nhóm luôn cũng được

**Comment by TranNgocBich99** [comment]
Đề tài:
Theo mình là nên chọn đề tài đơn giản vừa sức thôi như: làm trang quản lý khách sạn chẳng hạn.
Tên nhóm:
Có thể lấy chữ cái đầu của tên mỗi bạn trong nhóm để làm tên khách sạn hoặc tên nhóm luôn cũng được

**Comment by nguyenthihue269** [comment]
Tớ thấy hợp lý, chọn đề tài quản lý khách sạn oke rồi.

**Comment by trangvu9905** [comment]
Theo mình nghĩ thì làm website bán hàng thì khá phổ biến rồi, quản lý sinh viên... còn quản lý khách sạn thì mình thấy khá hợp lý vì nó có nhiều phần xử lý vì thế mình nên cần tìm hiểu nhiều

**Comment by trangvu9905** [comment]
> Đề tài:
> Theo mình là nên chọn đề tài đơn giản vừa sức thôi như: làm trang quản lý khách sạn chẳng hạn.
> Tên nhóm:
> Có thể lấy chữ cái đầu của tên mỗi bạn trong nhóm để làm tên khách sạn hoặc tên nhóm luôn cũng được

Đặt tên như này rất hay và sáng tạo nhé

**Comment by TrangMai288** [comment]
Mình nghĩ nên cho bạn Ngọc Bích làm master scrum vì bạn ấy có khả năng chỉ đạo mọi người và có tư duy lập trình tốt

**Comment by TrangMai288** [comment]
Đề tài khách sạn theo mình thấy sẽ có những khó khăn trong phần book phòng nhưng mình nghĩ bọn mình có thể cố gắng và làm tốt

**Comment by TranNgocBich99** [comment]
**Kết quả lịch họp 21/10/2019**

**Comment by TranNgocBich99** [comment]
### **Kết quả lịch họp 21/10/2019**

- Đề tài: Quản lý khách sạn
- Tên nhóm: TBH-Hotel
- Master Scrum: @TranNgocBich99
