### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#10]
1. Quản lý: Quản lý tài khoản, quản lý phòng, quản lý danh mục, quản lý hóa đơn
2. Nhân viên: Đặt phòng, hủy phòng, tra cứu phòng, tàm thủ tục checkin, checkout, lập hóa đơn cho khách hàng, 
3. Khách hàng có thể đặt phòng, hủy phòng, checkin, checkout và thanh toán.
![tbh2](https://user-images.githubusercontent.com/56257992/69433543-5ca37000-0d6e-11ea-8979-8a49b2ee4bf0.png)

**Comment by trangvu9905** [comment]
Mình chia là mỗi nhân viên thôi hả @TranNgocBich99
