### ISSUE TITLE
Biên bản họp Thống nhất code Backend 27/11/2019

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#11]
- Kết nối CSDL
- Thêm, sửa, xóa phòng

**Comment by trangvu9905** [comment]
@TrangMai288  cần sửa lại phần database chứ cái đấy còn sai nhiều lắm

**Comment by TranNgocBich99** [comment]
> @TrangMai288 cần sửa lại phần database chứ cái đấy còn sai nhiều lắm

thêm DB vào đi c, nhắn với Huệ để sửa chính xác nhé

**Comment by nguyenthihue269** [comment]
Sau khi họp thống nhất code backend, nhóm mình đã đưa ra công việc code các chức năng như sau:
Kết nối với DB
Liệt kê danh sách, thêm, xóa, sửa các phần: Quản lý phòng, quản lý danh mục, quản lý tài khoản, quản lý hóa đơn
Chức năng tìm kiếm ( tìm kiếm theo tên và thông tin của phòng )
Phân danh mục loại phòng ( liệt kê danh sách các phòng nằm trong danh mục phòng của khách sạn )
Xem chi tiết phòng, danh mục
Đăng nhập, đăng ký, đăng xuất ( có validate các mục như đúng định dạng email, mật khẩu ko đc nhỏ hơn 6 ký tự... và khi khách hàng vào đăng ký  để mặc định quyền của khách hàng; khi admin thêm tài khoản mới có thêm phần chọn quyền)
Đặt phòng ( Tìm phòng theo ngày cần đặt, sau đó đặt các phòng còn trống )
Phân quyền người dùng ( quản lý có quyền thêm, xóa, sửa mọi phòng, danh mục, tài khoản, hóa đơn; Nhân viên có quyền thêm phòng, xóa và sửa các phòng do người đó tạo ra và đổi mật khẩu tài khoản của họ; Khách hàng chỉ có quyền đổi mật khẩu tài khoản của họ )
Upload file ( Upload file ảnh để phục vụ việc thêm, sửa phòng danh mục )

**Comment by TrangMai288** [comment]
> @TrangMai288 cần sửa lại phần database chứ cái đấy còn sai nhiều lắm

Cậu cần sửa cái nào thì bảo tớ để tớ sửa

**Comment by trangvu9905** [comment]
Chúng ta nên thống nhất làm các chức năng:
1, Kết nối DB
2, Quản lý người dùng, phân quyền cho người dùng
3, Quản lý khách hàng: 
     + Quản lý thông tin khách hàng: tên KH, giới tính, địa chỉ, email, sđt, loại phòng, số lượng đặt phòng . ..
     + Nhân viên: nhập thông tin KH đến, in danh sách những KH đang ở, tìm kiếm KH theo phòng, tên...
4, Quản lý loại phòng: mã phòng, loại phòng, giá, tên KH sử dụng phòng, loại phòng, số phòng khách đặt, loại giường....
5,Quản lý hệ thống:
      + Quản lý đăng ký thuê phòng: thông tin thuê phòng dựa trên số đăng ký ngày giờ đi, đến
      + Quản lý trả phòng: dựa trên thông tin đăng ký thuê phòng, KH có thể trả phòng trước thời gian đăng ký hoặc gia hạn thêm thời gian
      + Quản lý hủy đăng ký: KH đã đăng ký phòng nhưng không muốn đến thì có thể hủy đăng ký đặt phòng.
6, Đăng ký, đăng nhập, validate các form
