### ISSUE TITLE
Code & UI

### ISSUE THREAD

**Issue by nguyenthihue269** [TranNgocBich99/TBH-HOTEL#12]

**Comment by nguyenthihue269** [comment]
Phần giao diện tớ đã tích hợp hết vào code backend các cậu ạ. Còn phần code chức năng t đã code được các chức năng sau:
- Kết nối DB
- Liệt kê danh sách, thêm, xóa, sửa phòng
- Liệt kê danh sách các danh mục
- Tìm kiếm theo tên và thông tin của phòng
- Phân danh mục
- Upload file

**Comment by TranNgocBich99** [comment]
Nếu cần thêm giao diện nào cậu cứ nói với tớ nhé

**Comment by TrangMai288** [comment]
> Phần giao diện tớ đã tích hợp hết vào code backend các cậu ạ. Còn phần code chức năng t đã code được các chức năng sau:
> 
> * Kết nối DB
> * Liệt kê danh sách, thêm, xóa, sửa phòng
> * Liệt kê danh sách các danh mục
> * Tìm kiếm theo tên và thông tin của phòng
> * Phân danh mục
> * Upload file

oke, tớ thấy rồi cậu nhé
