### ISSUE TITLE
Tìm hiểu cách đặt phòng

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#13]

**Comment by TranNgocBich99** [comment]
Theo tớ thì phần này khá khó, nên để làm sau, vì thế mọi người nên tìm hiểu dần cho kịp tiến độ

**Comment by nguyenthihue269** [comment]
Ukm, phần này tớ cũng chưa biết cách làm với việc chọn ngày trong lịch, tớ tìm hiểu thêm về phần này nhé

**Comment by nguyenthihue269** [comment]
Theo tớ thì khi khách hàng vào đặt phòng thì sẽ có phần được chọn ngày đặt phòng, khi người đó chọn ngày ( gồm có ngày đến và ngày đi ) thì sẽ liệt kê ra các phòng mà những ngày đó chưa có ai đặt và họ chỉ đặt được những phòng đấy

**Comment by TrangMai288** [comment]
Theo tớ thì nên làm xong các mục nhỏ thì về sau sẽ làm trọng tâm cái này

**Comment by TrangMai288** [comment]
Phần đặt phòng này sẽ là phần tiêu điểm cho đề tài này nên là cần có thời gian tìm hiểu vấn đề rồi code nữa. Đặt phòng theo tớ thấy thì nó liên kết đến nhiều cái như phòng, dịch vụ phòng, ... nên là làm chắc những issue cũ thì mới làm được cái này. Cố lên các cậu ơiiii

**Comment by trangvu9905** [comment]
Mình có xem phần đặt phòng ở 1 số trang website, tuy nhiên thì mình thấy phần này khá khó nên nhóm sẽ xử lý sau. Trước mắt mình cứ làm các phần dễ để hoàn thiện sau nhé

**Comment by TranNgocBich99** [comment]
phần này nên để làm cuối cùng là hợp lý nhất
