### ISSUE TITLE
Tìm hiểu cách đánh giá sao cho các phòng và comment

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#14]

**Comment by TranNgocBich99** [comment]
Phần này tớ nghĩ nên nghiên cứu dần cách làm và  cũng không quá khó nhỉ

**Comment by TrangMai288** [comment]
Cái comment này tớ chưa làm bao giờ nên cũng hơi bỡ ngỡ 😅 Bạn Hạnh Trang với Huệ từng làm rồi thì hai cậu cho ý kiến với cách làm để bọn mình cùng tìm hiểu nhé :))

**Comment by trangvu9905** [comment]
Phần comment mình đã từng làm rồi, có gì mình sẽ phụ trách làm phần này nhé

**Comment by trangvu9905** [comment]
Còn phần đánh giá sao thì mình chưa làm bao giờ, vì thế mình sẽ tìm hiểu và giúp đỡ nhau nhá

**Comment by nguyenthihue269** [comment]
Uk mình cũng chưa làm phần đánh giá sao, mình sẽ tìm hiểu thêm

**Comment by TranNgocBich99** [comment]
tìm hiểu phần này chắc cũng phức tạp
