### ISSUE TITLE
Ghép code vào giao diện đăng ký, đăng nhập bị lỗi

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#15]
Phần đăng ký, đăng nhập khá phức tạp nên mọi người cố gắng tập trung ghép code cẩn thận tránh xảy ra lỗi

**Comment by TrangMai288** [comment]
Được oke cậu nhé

**Comment by trangvu9905** [comment]
Mình đang ghép code mà bị lỗi css

**Comment by trangvu9905** [comment]
Sẽ cố gắng fix lỗi phần đó nhé

**Comment by TranNgocBich99** [comment]
> Sẽ cố gắng fix lỗi phần đó nhé

Cậu có thể hỏi trực tiếp Huệ nhé, Huệ từng fix được lỗi này rồi

**Comment by nguyenthihue269** [comment]
Theo tớ thì có thể tên 2 class của css trùng nhau nên nó bị lỗi, cậu thử bỏ link css file đăng nhập, đăng ký ở header đi và cho vào đầu file đăng kí đăng nhập xem sao nhé

**Comment by nguyenthihue269** [comment]
à c xem sửa nhanh nhé, vì phần đăng kí, đăng nhập còn liên quan đến phần phân quyền nên code nhanh để kịp tiến độ, và phần phân quyền làm rất nhiều thời gian.

**Comment by nguyenthihue269** [comment]
Phần này t đã sửa vào push code lên git rồi nhé, cc xem nhé
