### ISSUE TITLE
Tập trung code để ôn thi cuối kỳ

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#16]
Do lịch thi của bọn mình khá nhiều và khá gấp nên cần đẩy nhanh tiến độ code để sớm hoàn thành sản phẩm và còn ôn thi nữa.

**Comment by TrangMai288** [comment]
Ừ oke, thế ngày mai bọn mình đến lớp thì phân chia luôn nhé. Cố gắng làm xong trong thời gian sớm nhất

**Comment by trangvu9905** [comment]
Kỳ này chúng ta học khá nhiều môn và lịch thi dày đặc nên cần phải biết sắp xếp và phân bổ thời gian hợp lí để đạt hiệu quả tốt

**Comment by trangvu9905** [comment]
Chúng ta phải đẩy nhanh tiến độ để còn check bug nữa

**Comment by trangvu9905** [comment]
Ngày mai cần một buổi họp gấp nhé các cậu @TranNgocBich99  @TrangMai288  @nguyenthihue269

**Comment by TranNgocBich99** [comment]
> Ngày mai cần một buổi họp gấp nhé các cậu @TranNgocBich99 @TrangMai288 @nguyenthihue269

Oke cậu, cần chia code để đẩy nhanh tiến độ

**Comment by nguyenthihue269** [comment]
uk chia ra mỗi người làm 1 phần cho nhanh
