### ISSUE TITLE
Một số bảng trong Database bị thừa một số trường 

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#17]
Một số bảng bị thừa một số trường không cần thiết như bảng room... bạn @TrangMai288  cần sửa và tiếp tục đổ thêm DB vào, tránh trường hợp bảng bị thừa dữ liệu gây khó khăn cho việc code

**Comment by nguyenthihue269** [comment]
Tớ thấy bảng room thừa trường ngày đến và ngày đi, bảng category thiếu trường images. 2 bảng này tớ code backend nên sửa rồi, còn mấy bảng kia c sửa lại nhé. Vì vừa code vừa sửa sẽ rất lâu

**Comment by TranNgocBich99** [comment]
> Tớ thấy bảng room thừa trường ngày đến và ngày đi, bảng category thiếu trường images. 2 bảng này tớ code backend nên sửa rồi, còn mấy bảng kia c sửa lại nhé. Vì vừa code vừa sửa sẽ rất lâu

@TrangMai288  vào sửa nhanh lên bạn
