### ISSUE TITLE
Tiếp tục cập nhật và sửa Database

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#18]
Database cần sửa và bổ sung nhiều mọi người tiếp tục nêu ý kiến và sửa cho đúng nhé

**Comment by TrangMai288** [comment]
Các cậu ơi, tớ đã sửa những phần các cậu bảo rồi. Giờ tớ đang chèn dữ liệu vào DB thì có những điều tớ muốn bàn với các cậu đó là:
1. **Bảng roles** thì có phần phân quyền thì các cậu muốn cho phân những quyền gì?
2. **Bảng room_category** thì chúng ta có những loại phòng gì thế?
3. **Bảng service** dùng để nói về dịch vụ phòng thì các cậu định cho những loại dịch vụ gì?
Cho tớ ý kiến sớm để tớ chèn nha 
Many thanks ♥♥♥

**Comment by TrangMai288** [comment]
@trangvu9905 @TranNgocBich99  @nguyenthihue269  Các cậu comment để cho mình xin ý kiến nha ♥

**Comment by trangvu9905** [comment]
> Các cậu ơi, tớ đã sửa những phần các cậu bảo rồi. Giờ tớ đang chèn dữ liệu vào DB thì có những điều tớ muốn bàn với các cậu đó là:
> 
> 1. **Bảng roles** thì có phần phân quyền thì các cậu muốn cho phân những quyền gì?
> 2. **Bảng room_category** thì chúng ta có những loại phòng gì thế?
> 3. **Bảng service** dùng để nói về dịch vụ phòng thì các cậu định cho những loại dịch vụ gì?
>    Cho tớ ý kiến sớm để tớ chèn nha
>    Many thanks ♥♥♥

Bảng role theo mình thì sẽ phân ra làm 3 quyền: Giám đốc, nhân viên, khách hàng

**Comment by trangvu9905** [comment]
Bảng room_category chia làm 3 loại phòng: 
+ Phòng Standard (STD): Standard - phòng tiêu chuẩn trong khách sạn, là loại phòng đơn giản nhất với những trang bị tối thiểu, có diện tích nhỏ, ở tầng thấp, không có view hoặc view không đẹp.
+ Phòng Superior (SUP): loại phòng có chất lượng cao hơn STD với diện tích lớn hơn, được trang bị nhiều trang thiết bị tiện nghi, có view đẹp.
+ Phòng Deluxe (DLX): oại phòng này thường ở trên tầng cao với chất lượng tốt hơn phòng Superior. Phòng Deluxe có diện tích rộng, có tầm nhìn đẹp với các trang thiết bị cao cấp

**Comment by trangvu9905** [comment]
Bảng service chia làm 3 loại dịch vụ phòng: Tiêu chuẩn, Chất lượng, Chất lượng cao

**Comment by nguyenthihue269** [comment]
1. Tớ cũng nghĩ phân làm 3 quyền: admin, nhân viên và khách hàng.
2. Có 5 loại danh mục 
![image](https://user-images.githubusercontent.com/56260042/71156564-d26a0100-2272-11ea-880f-43b13943b4c1.png)

**Comment by TrangMai288** [comment]
> > Các cậu ơi, tớ đã sửa những phần các cậu bảo rồi. Giờ tớ đang chèn dữ liệu vào DB thì có những điều tớ muốn bàn với các cậu đó là:
> > 
> > 1. **Bảng roles** thì có phần phân quyền thì các cậu muốn cho phân những quyền gì?
> > 2. **Bảng room_category** thì chúng ta có những loại phòng gì thế?
> > 3. **Bảng service** dùng để nói về dịch vụ phòng thì các cậu định cho những loại dịch vụ gì?
> >    Cho tớ ý kiến sớm để tớ chèn nha
> >    Many thanks ♥♥♥
> 
> Bảng role theo mình thì sẽ phân ra làm 3 quyền: Giám đốc, nhân viên, khách hàng

Phần "Giám đốc" thì tớ để là admin nghe cho quen thuộc nhé cậu

**Comment by nguyenthihue269** [comment]
5 loại danh mục này là theo thiết kế Bích làm giao diện, còn bảng service thì t nghĩ là giường phụ, wifi,...

**Comment by TrangMai288** [comment]
> 5 loại danh mục này là theo thiết kế Bích làm giao diện, còn bảng service thì t nghĩ là giường phụ, wifi,...

Ừ, tớ cũng nghĩ thế tại kiểu dịch vụ thì sẽ là thêm mấy cái giường, đồ uống hoặc giặt ủi í.
@TranNgocBich99  bạn thử nêu thêm ý kiến để mình làm bảng service nhé

**Comment by trangvu9905** [comment]
> 1. Tớ cũng nghĩ phân làm 3 quyền: admin, nhân viên và khách hàng.
> 2. Có 5 loại danh mục
>    ![image](https://user-images.githubusercontent.com/56260042/71156564-d26a0100-2272-11ea-880f-43b13943b4c1.png)

Huệ ơi, đổi về Tiếng Việt hết đi

**Comment by TranNgocBich99** [comment]
> > 5 loại danh mục này là theo thiết kế Bích làm giao diện, còn bảng service thì t nghĩ là giường phụ, wifi,...
> 
> Ừ, tớ cũng nghĩ thế tại kiểu dịch vụ thì sẽ là thêm mấy cái giường, đồ uống hoặc giặt ủi í.
> @TranNgocBich99 bạn thử nêu thêm ý kiến để mình làm bảng service nhé

mấy cái dịch vụ phức tạp quá thì để sau vậy, mình nghĩ trước tiên là nên làm các dịch vụ như cung cấp khăn tắm, chăn, gối, ấm điện,......
