### ISSUE TITLE
Tìm hiểu ajax

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#19]
Đây là một công nghệ giúp chung ta tạo ra những Web động mà hoàn toàn không reload lại trang nên rất mượt và đẹp, mọi người nên tìm hiểu

**Comment by TrangMai288** [comment]
Mình nghĩ là bọn mình nên dành thời gian tầm 1 ngày để tìm hiểu, mình cũng mới xem qua cách sử dụng thì thấy AJAX khá giống với JavaScript nên chắc cũng không khó khăn lắm

**Comment by TrangMai288** [comment]
Mình sẽ cố gắng tìm hiểu sơ bộ cách thức code và hoạt động của AJAX xong sau đó bọn mình họp lại để bàn xem sử dụng ghép code như nào nhé

**Comment by TranNgocBich99** [comment]
> Mình sẽ cố gắng tìm hiểu sơ bộ cách thức code và hoạt động của AJAX xong sau đó bọn mình họp lại để bàn xem sử dụng ghép code như nào nhé

Oke cậu, mình nghĩ nên ghép luôn cho kịp tiến độ

**Comment by nguyenthihue269** [comment]
uk t cũng thấy phần này rất hay, chúng ta nên tìm hiểu
