### ISSUE TITLE
Thiết kế giao diện

### ISSUE THREAD

**Issue by nguyenthihue269** [TranNgocBich99/TBH-HOTEL#2]

**Comment by TranNgocBich99** [comment]
Các công nghệ mà cần phải sử dụng theo mình là: CSS, HTML, JS, BS4....
Còn về việc thiết kế thì nên tham khảo các trang trên mạng.

**Comment by nguyenthihue269** [comment]
Thiết kế giao diện gồm có 2 phần: 
+ Frontend
+ Backend
Theo mình nghĩ nên đặt ra thời gian để làm ví dụ thiết kế giao diện trong 1 tuần xong chuyển qua code backend
Phần làm giao diện này sẽ phân chia nhau mỗi người làm 1-2 trang cho nhanh.
Giao diện gồm có các trang: Trang chủ, chi tiết sản phẩm, đặt phòng danh mục, giới thiệu, liên hệ, tìm kiếm, trang quản trị,...
Song song với việc làm giao diện thì 1 bạn sẽ thiết kế database rồi các bạn trong nhóm cho ý kiến nhé.
Các cậu đóng góp ý kiến nhé :)

**Comment by TranNgocBich99** [comment]
Theo t thì nên tham khảo các trang web quản lý khách sạn trên mạng, xong rồi mình sé sửa đổi sao cho phù hợp
Phần front-end làm 1-2 người cũng được, nhưng phải làm khẩn trương trong tuần này luôn nha, mình sắp thi giữa kỳ rồi đó
Các cậu thấy thế nào?

**Comment by trangvu9905** [comment]
> Các công nghệ mà cần phải sử dụng theo mình là: CSS, HTML, JS, BS4....
> Còn về việc thiết kế thì nên tham khảo các trang trên mạng.

Theo mình thì chúng ta sẽ dựa trên một trang có sẵn nào đấy và làm theo

**Comment by trangvu9905** [comment]
> Thiết kế giao diện gồm có 2 phần:
> 
> * Frontend
> * Backend
>   Theo mình nghĩ nên đặt ra thời gian để làm ví dụ thiết kế giao diện trong 1 tuần xong chuyển qua code backend
>   Phần làm giao diện này sẽ phân chia nhau mỗi người làm 1-2 trang cho nhanh.
>   Giao diện gồm có các trang: Trang chủ, chi tiết sản phẩm, đặt phòng danh mục, giới thiệu, liên hệ, tìm kiếm, trang quản trị,...
>   Song song với việc làm giao diện thì 1 bạn sẽ thiết kế database rồi các bạn trong nhóm cho ý kiến nhé.
>   Các cậu đóng góp ý kiến nhé :)

Theo mình muốn làm trang đẹp thì cần phải có mẫu và từ đó dựa làm theo, nhưng cần phải đảm bảo theo các tiêu chí là: dễ nhìn, thoáng và sắp xếp bố cục hợp lý chút

**Comment by TrangMai288** [comment]
Mình nghĩ là trang giao diện nên được làm và tính toán kĩ để mai sau khi làm sẽ dễ áp dụng vào code hơn

**Comment by nguyenthihue269** [comment]
Phần giao diện mình và Bích đã làm xong và push lên git rồi, các cậu vào xem có gì chỉnh sửa ko nhé :)

**Comment by TranNgocBich99** [comment]
Hai bạn làm DB push lên đi cho mọi người cùng bàn luận
