### ISSUE TITLE
Các chức năng chưa làm

### ISSUE THREAD

**Issue by nguyenthihue269** [TranNgocBich99/TBH-HOTEL#21]

**Comment by nguyenthihue269** [comment]
Dưới đây, tớ liệt kê danh sách các chức năng của project mà nhóm mình chưa làm hoặc đang làm:
- Đăng ký tài khoản
- Đăng nhập tài khoản
- Phân quyền người dùng
- Quản lý tài khoản ( trang quản trị )
- Đặt phòng
- Quản lý hóa đơn ( trang quản trị )

**Comment by TranNgocBich99** [comment]
> Dưới đây, tớ liệt kê danh sách các chức năng của project mà nhóm mình chưa làm hoặc đang làm:
> 
> * Đăng ký tài khoản
> * Đăng nhập tài khoản
> * Phân quyền người dùng
> * Quản lý tài khoản ( trang quản trị )
> * Đặt phòng
> * Quản lý hóa đơn ( trang quản trị )

Có vẻ hơi nhiều nhỉ, không biết có kịp không :((((

**Comment by trangvu9905** [comment]
> Dưới đây, tớ liệt kê danh sách các chức năng của project mà nhóm mình chưa làm hoặc đang làm:
> 
> * Đăng ký tài khoản
> * Đăng nhập tài khoản
> * Phân quyền người dùng
> * Quản lý tài khoản ( trang quản trị )
> * Đặt phòng
> * Quản lý hóa đơn ( trang quản trị )

Cố gắng làm các chức năng quan trọng để hoàn thiện bài

**Comment by nguyenthihue269** [comment]
Hiện tại các chức năng nhóm mình chưa làm:
- Đặt phòng
- Quản lý hóa đơn
- Sửa, xóa user phần quản lý tài khoản
