### ISSUE TITLE
Validate form đăng ký, đăng nhập tài khoản

### ISSUE THREAD

**Issue by nguyenthihue269** [TranNgocBich99/TBH-HOTEL#22]

**Comment by nguyenthihue269** [comment]
Khi mà submit form đăng nhập đăng ký thì phải theo yêu cầu và có tính hợp lệ. Theo tớ thì form đăng ký gồm các trường email, tài khoản mật khẩu, Các trường này phải thỏa mãn điều kiện: email ko đc trống và đúng định dạng email và chưa tồn tại. Tên tài khoản phải lớn hơn 6 ký tự và cũng chưa tồn tại không đc trống. Mật khẩu phải lớn hơn 6 ký tự, không đc trống và 2 ô nhập mật khẩu và nhập lại mật khẩu phải giống nhau. 
Các cậu cho ý kiến validate form đăng ký nhé <3

**Comment by TranNgocBich99** [comment]
Có nên làm luôn mấy cái cảnh báo như khi nhập tên tài khoản không đủ số ký tự, email không đúng định dạng  thì nó hiện lên thông báo đỏ luôn không nhỉ.

**Comment by trangvu9905** [comment]
Bài của mình cần validate các trường: email, mật khẩu, nhập lại mật khẩu, tên đăng nhập. Email thì phải không được trống, định dạng đúng hay chưa, chưa tồn tại. Mật khẩu thì không được trống, >8. Nhập lại mật khẩu thì phải chính xác với mật khẩu trên. Tên đăng nhập: không được trống, >5. Và thông báo lỗi màu đỏ.

**Comment by nguyenthihue269** [comment]
![image](https://user-images.githubusercontent.com/56260042/71506771-dcb07e80-28b4-11ea-8c50-8385828145f1.png)
Validate báo lỗi này đc ko cc

**Comment by nguyenthihue269** [comment]
![image](https://user-images.githubusercontent.com/56260042/71506845-1d0ffc80-28b5-11ea-9f49-b186e1f967f3.png)

**Comment by trangvu9905** [comment]
Ok. Khá ổn cậu nhé
