### ISSUE TITLE
Quản lý hóa đơn

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#23]
Phần này thì làm quản lý các phần như thông tin khách hàng, thanh toán, danh mục các sản phẩm đã sử dụng...

**Comment by trangvu9905** [comment]
Ok. Phần này quản lý hóa đơn cũng phải đầy đủ các thông tin

**Comment by TrangMai288** [comment]
Phần quản lý hóa đơn sẽ là danh mục bao gồm hầu hết các thông tin và sẽ do admin quản lý
