### ISSUE TITLE
Quản lý tài khoản

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#24]
Thêm, sửa, xóa các user

**Comment by nguyenthihue269** [comment]
Phần này mình làm phần thêm user rồi nhé các cậu
Còn sửa và xóa user nữa

**Comment by TrangMai288** [comment]
Mình đã làm phần xóa rồi nhé cậu

**Comment by TrangMai288** [comment]
Còn phần sửa thông tin user thì mình vẫn đang bị lỗi các cậu ạ
