### ISSUE TITLE
Chỉnh sửa màu menu đa cấp 

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#25]
Màu cũ là màu trắng nó khó nhìn quá nên mình đã chuyển sang màu tối hơn

**Comment by TranNgocBich99** [comment]
các bạn xem được chưa
![aaa](https://user-images.githubusercontent.com/56257992/71769019-68c64400-2f4e-11ea-942d-cadde10c5f17.png)

**Comment by trangvu9905** [comment]
Được đấy Bích, nhưng phần phòng nghỉ đổi tên các loại phòng thành Tiếng Viết hết đi nhé

**Comment by TrangMai288** [comment]
Mình thấy đẹp và dễ nhìn hơn rồi đó
