### ISSUE TITLE
Test Validate form Đăng ký, Đăng nhập

### ISSUE THREAD

**Issue by nguyenthihue269** [TranNgocBich99/TBH-HOTEL#26]
Tỡ làm xong phần đăng ký, đăng nhập nhé. 
Ở phần đăng ký validate form theo các yêu cầu sau: Tài khoản, mật khẩu, email không được trống;
Tài khoản & mật khẩu phải lớn hơn hoặc bằng 6 ký tự. Tài khoản và email không được trùng với các tài khoản và email đã có; Email phải đúng định dạng; 2 ô Nhập mật khẩu và xác nhạp mật khẩu phải giống nhau. => Nếu sai thì sẽ báo lỗi 
Ở phần đăng nhập validate form theo yêu cầu: Tài khoản và mật khẩu phải trùng với các tài khoản đã được đăng ký; Tài khoản và mật khẩu không được trống.=> Nếu sai sẽ báo lỗi
Các bạn cho tớ ý kiến có gì t sửa lại nhé :)

**Comment by nguyenthihue269** [comment]
![image](https://user-images.githubusercontent.com/56260042/71799414-c611e080-3087-11ea-8c14-64cc54a19709.png)

**Comment by nguyenthihue269** [comment]
![image](https://user-images.githubusercontent.com/56260042/71799451-e93c9000-3087-11ea-914a-f13a5d0e5522.png)

**Comment by nguyenthihue269** [comment]
![image](https://user-images.githubusercontent.com/56260042/71799490-02ddd780-3088-11ea-874b-935ea93b87db.png)

**Comment by nguyenthihue269** [comment]
![image](https://user-images.githubusercontent.com/56260042/71799508-17ba6b00-3088-11ea-8fee-8b798bb2f02d.png)

**Comment by nguyenthihue269** [comment]
Trên đây mình gửi một số ảnh validate form đăng ký, đăng nhập nhé các cậu

**Comment by trangvu9905** [comment]
Ok Huệ.

**Comment by trangvu9905** [comment]
Phần validate các trường dữ liệu trong form đăng ký, đăng nhập như vậy là ổn rồi

**Comment by TranNgocBich99** [comment]
tối tớ sẽ test lại nhé

**Comment by TrangMai288** [comment]
Mình thấy Huệ làm oke rồi đó
