### ISSUE TITLE
Thiết kế cơ sở dữ liệu

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#3]
Thiết kế cơ sở dữ liệu cho trang quản lý khách sạn
Chọn các bảng, các trường, khóa chính, khóa ngoại, các ràng buộc ... cho phù hợp

**Comment by trangvu9905** [comment]
Mình sẽ thiết kế databases rồi sẽ gửi lại cho các bạn xem lại nhé

**Comment by TranNgocBich99** [comment]
@trangvu9905 Cậu cố làm hết tuần này mà xong được là oke

**Comment by trangvu9905** [comment]
> @trangvu9905 Cậu cố làm hết tuần này mà xong được là oke

Ok. Mình với Trang mai sẽ làm cùng nhau và sẽ gửi cho tất cả chúng ta cùng chốt nhé
:)

**Comment by TrangMai288** [comment]
mình với bạn Hạnh Trang sẽ tập trung và thảo luận làm database nhé các cậu

**Comment by trangvu9905** [comment]
Các bạn ơi, hiện tại mình đã làm database cho các phần như sau: bộ sưu tập cho các phòng, kiểm kê phòng vào ra, kiểm kê phòng còn trống, thông tin người dùng, xem chi tiết phòng và phần tinh nhắn của khách.
@nguyenthihue269 @TranNgocBich99 @TrangMai288 
Các bạn vào xem giúp mình với nhé

**Comment by TranNgocBich99** [comment]
> Các bạn ơi, hiện tại mình đã làm database cho các phần như sau: bộ sưu tập cho các phòng, kiểm kê phòng vào ra, kiểm kê phòng còn trống, thông tin người dùng, xem chi tiết phòng và phần tinh nhắn của khách.
> @nguyenthihue269 @TranNgocBich99 @TrangMai288
> Các bạn vào xem giúp mình với nhé

theo t thì nên làm thêm phần ưu đãi nữa cậu

**Comment by nguyenthihue269** [comment]
Theo tớ thì nên thêm phần danh mục hay phân chia các loại phòng.

**Comment by nguyenthihue269** [comment]
Và thêm 1 bảng hóa đơn nữa, sẽ lưu các phòng được đặt, người đặt phòng đó và tổng số tiền,...

**Comment by trangvu9905** [comment]
> Và thêm 1 bảng hóa đơn nữa, sẽ lưu các phòng được đặt, người đặt phòng đó và tổng số tiền,...

Cái đấy mình 

> > Các bạn ơi, hiện tại mình đã làm database cho các phần như sau: bộ sưu tập cho các phòng, kiểm kê phòng vào ra, kiểm kê phòng còn trống, thông tin người dùng, xem chi tiết phòng và phần tinh nhắn của khách.
> > @nguyenthihue269 @TranNgocBich99 @TrangMai288
> > Các bạn vào xem giúp mình với nhé
> 
> theo t thì nên làm thêm phần ưu đãi nữa cậu

Ok mình sẽ bổ sung thêm nhé

**Comment by trangvu9905** [comment]
> Theo tớ thì nên thêm phần danh mục hay phân chia các loại phòng.

Ok. Mình ghi nhận nhé

**Comment by trangvu9905** [comment]
> Và thêm 1 bảng hóa đơn nữa, sẽ lưu các phòng được đặt, người đặt phòng đó và tổng số tiền,...
Mình sẽ bổ sung thêm nhé

**Comment by trangvu9905** [comment]
Mình làm xong database rồi nhé. Mai mình sẽ gửi lên cho các bạn xem rồi nhận xét nhé
@TrangMai288 @TranNgocBich99 @nguyenthihue269

**Comment by nguyenthihue269** [comment]
Trang Vũ và Trang Mai ơi, nếu 2 bạn làm xong database rồi thì gửi lên cả nhóm tham khảo và đưa ra ý kiến nhé, nếu giao diện và database xong rồi thì nhóm mình chuyển qua code backend nhé

**Comment by TranNgocBich99** [comment]
> Trang Vũ và Trang Mai ơi, nếu 2 bạn làm xong database rồi thì gửi lên cả nhóm tham khảo và đưa ra ý kiến nhé, nếu giao diện và database xong rồi thì nhóm mình chuyển qua code backend nhé

cứ thống nhất xong DB đã c ơi

**Comment by TrangMai288** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/50409563/68365053-3a9cd180-0162-11ea-8753-0d6222cc5ad7.png)

**Comment by TrangMai288** [comment]
Đây là DB của mình
Các bạn đóng góp ý kiến để mình hoàn thiện hơn nhé

**Comment by TranNgocBich99** [comment]
> Đây là DB của mình
> Các bạn đóng góp ý kiến để mình hoàn thiện hơn nhé
Mình nghĩ cần bổ sung thêm phần Sale nữa: sale theo %, sale theo số tiền chẳng hạn

**Comment by TranNgocBich99** [comment]
> Đây là DB của mình
> Các bạn đóng góp ý kiến để mình hoàn thiện hơn nhé

**Comment by TranNgocBich99** [comment]
Mình nghĩ cần bổ sung thêm phần sale nữa: như sale trừ theo % hay trừ sale theo giá tiền

**Comment by nguyenthihue269** [comment]
Theo tớ thì ko cần chia ra hai bảng bills_detail và bills. Vì hai bảng này có thể viết thành một bảng, sau đó khi vào xem hóa đơn sẽ select ra 1 vài trường tiêu biểu như guest, room & price, còn nếu vào xem chi tiết hóa đơn thì select ra tất cả các trường trong bảng đó. 
Trong bảng room còn thiếu  trường là image vì cần up file ảnh phòng lên trang web.
Và tớ nghĩ không nên để bảng room_image vì bảng này lại nối với bảng category, nên để trường image trong bảng category để không phải join hai bảng 
Các bảng là bảng chính nên thêm 1 trường là is_deleted để sau này xử lý phần xóa cứng và xóa mềm.
Trên đây là những ý kiến của tớ hihi

**Comment by TranNgocBich99** [comment]
> Theo tớ thì ko cần chia ra hai bảng bills_detail và bills. Vì hai bảng này có thể viết thành một bảng, sau đó khi vào xem hóa đơn sẽ select ra 1 vài trường tiêu biểu như guest, room & price, còn nếu vào xem chi tiết hóa đơn thì select ra tất cả các trường trong bảng đó.
> Trong bảng room còn thiếu trường là image vì cần up file ảnh phòng lên trang web.
> Và tớ nghĩ không nên để bảng room_image vì bảng này lại nối với bảng category, nên để trường image trong bảng category để không phải join hai bảng
> Các bảng là bảng chính nên thêm 1 trường là is_deleted để sau này xử lý phần xóa cứng và xóa mềm.
> Trên đây là những ý kiến của tớ hihi

t cũng đồng ý với ý kiến của Huệ
Cố thiết lế DB cho mạch lạc, để code cho dễ

**Comment by TrangMai288** [comment]
Vậy bọn mình lấy khung là DB ở trên sau đó thêm những ý kiến của Huệ vào nhé
