### ISSUE TITLE
Các công nghệ sử dụng

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#4]

**Comment by TrangMai288** [comment]
Theo mình nghĩ thì nhóm mình nên code bằng ngôn ngữ PHP vì đây là ngôn ngữ khá dễ học và dễ sử dụng các lệnh, các bạn thấy sao?

**Comment by TranNgocBich99** [comment]
Theo mình thì có 1 số ý kiến như sau: 
- Mô hình nhóm mình sẽ là Scrum Team
- Công nghệ quản lý code là Git

**Comment by TrangMai288** [comment]
Và mình muốn thêm ý kiến đó là chúng ta sẽ sử dụng MySQL cho CSDL vì đây là hệ quản trị cơ sở dữ liệu dễ dùng và chúng mình cũng đã được học trong môn CSDL

**Comment by trangvu9905** [comment]
Theo mình thì chúng ta nên dùng PHP vì:
+ Dùng mã nguồn mở (có thể chạy trên Apache hoặc IIS).
+ Dễ học khi đã biết HTML, C.
+ Đi cặp với mySQL (cũng dễ ) vì đã được học rồi

**Comment by TranNgocBich99** [comment]
Front-end theo mình thì dùng:
- css
- html
- bootstrap 4
- jquery

**Comment by TranNgocBich99** [comment]
> Theo mình thì chúng ta nên dùng PHP vì:
> 
> * Dùng mã nguồn mở (có thể chạy trên Apache hoặc IIS).
> * Dễ học khi đã biết HTML, C.
> * Đi cặp với mySQL (cũng dễ ) vì đã được học rồi
