### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#5]
Mình vừa cập nhật file ReadMe.md

- Tên đề tài

- Mục tiêu, định hướng, các kết quả cần đạt được

- Công nghệ sử dụng

- Thành viên trong nhóm

**Comment by TrangMai288** [comment]
Theo các bạn thì mình có nên ghi thêm phác thảo chức năng tổng quát và giao diện người dùng không?

**Comment by trangvu9905** [comment]
> Theo các bạn thì mình có nên ghi thêm phác thảo chức năng tổng quát và giao diện người dùng khôn

**Comment by trangvu9905** [comment]
> Theo các bạn thì mình có nên ghi thêm phác thảo chức năng tổng quát và giao diện người dùng không?

Theo mình thì nên ghi các chức năng chính của trang website, cũng như các tính năng của người dùng nữa

**Comment by nguyenthihue269** [comment]
Ừ, theo mình thì nên nêu ra những ý chính về các chức năng và giao diện của trang web như 2 bạn nói ở trên.
