### ISSUE TITLE
Biên bản họp Thống nhất CSDL ngày 5/11/2019

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#7]
Những vấn đề được thống nhất về CSDL:

- Các trường cần được bổ sung như Đăng nhập, Đăng ký, Đặt phòng....

- Tiếp tục thay đổi các bảng cho phù hợp, loại bỏ 1 số bảng không cần thiết bị thừa như bảng nhân viên và người quản lý không cần tách ra 2 bảng 

- Thống nhất khóa ngoại các bảng

**Comment by nguyenthihue269** [comment]
> Những vấn đề được thống nhất về CSDL:
> 
> * Các trường cần được bổ sung như Đăng nhập, Đăng ký, Đặt phòng....
> * Tiếp tục thay đổi các bảng cho phù hợp, loại bỏ 1 số bảng không cần thiết bị thừa như bảng nhân viên và người quản lý không cần tách ra 2 bảng
> * Thống nhất khóa ngoại các bảng

t thấy nhóm mình đưa ra các thay đổi trên rất hợp lý

**Comment by TrangMai288** [comment]
Mình đồng ý với ý kiến của bạn Bích nhé!

**Comment by trangvu9905** [comment]
Phần CSDL thì nhóm mình cần chỉnh lại về phần khóa ngoại và những trường giữa các bảng.
Và các chức năng phân quyền về đăng nhập, các trường cho phần đăng ký cho hợp lý.

**Comment by TranNgocBich99** [comment]
> Phần CSDL thì nhóm mình cần chỉnh lại về phần khóa ngoại và những trường giữa các bảng.
> Và các chức năng phân quyền về đăng nhập, các trường cho phần đăng ký cho hợp lý.

theo mình thì nếu Trang Mai và Trang Vũ làm xong thì nên up ảnh lên hoặc commit vào nhánh database cũng dc, cho mọi người cùng nêu ý kiến
