### ISSUE TITLE
Biên bản họp Thống nhất giao diện 10/11

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#8]
Sau đây là nội dung thống nhất giao diện:

- Sử dụng các công nghệ Html, Css, Bootstrap4, JQuery...

- Thiết kế giao diện chính: trang chủ, giới thiệu, phòng nghỉ, Sale, Đặt phòng

- Bổ sung thêm giao diện đăng ký, đăng nhập...

- Sửa lại một số font chữ cho đẹp

**Comment by TrangMai288** [comment]
Mình đồng ý với nội dung của bạn Bích. Khi nào bạn Bích và Huệ làm tương đối xong thì gửi bản demo lên cho bọn tớ xem rồi mình cùng chỉnh sửa và cho ý kiến thêm nhé

**Comment by trangvu9905** [comment]
Phần giao diện đồng ý với ý kiến của Bích. Và Bích và Huệ làm xong rồi gửi bản demo để mội người xem và nhận xét để đưa ra phần kết luận nhé

**Comment by TranNgocBich99** [comment]
> Phần giao diện đồng ý với ý kiến của Bích. Và Bích và Huệ làm xong rồi gửi bản demo để mội người xem và nhận xét để đưa ra phần kết luận nhé

bọn mình đã commit lên nhánh front-end r, cậu vào xem và cho ý kiến hộ mình với

**Comment by nguyenthihue269** [comment]
mình đồng ý với các ý kiến góp ý của các bạn.

**Comment by TranNgocBich99** [comment]
![dk](https://user-images.githubusercontent.com/56257992/68674226-0d985680-0588-11ea-9ace-313a6151f296.png)
![dn](https://user-images.githubusercontent.com/56257992/68674227-0d985680-0588-11ea-9cf3-295c3bbc9ad9.png)
Mình thấy giao diện đăng nhập đăng ký này khá đầy đủ và sáng sủa, các bạn cho ý kiến

**Comment by nguyenthihue269** [comment]
MÌnh thấy giao diện đấy rất đẹp, nhưng nếu khi làm giao diện nên bỏ phần tiếp tục với facebook & google vì chúng mình chưa biết làm phần đó

**Comment by TranNgocBich99** [comment]
> MÌnh thấy giao diện đấy rất đẹp, nhưng nếu khi làm giao diện nên bỏ phần tiếp tục với facebook & google vì chúng mình chưa biết làm phần đó

mình cũng thấy thế, làm cái mà mình biết cho tốt đã

**Comment by trangvu9905** [comment]
![Capture](https://user-images.githubusercontent.com/56261142/68677537-d7aaa080-058e-11ea-89ed-0a6897198247.PNG)

**Comment by trangvu9905** [comment]
![Capture](https://user-images.githubusercontent.com/56261142/68677688-17718800-058f-11ea-8bcc-361e7d5ebd00.PNG)

**Comment by trangvu9905** [comment]
Mình thấy form đăng ký, đăng nhập làm đơn giản cũng được, phần đăng nhập bằng facebook, đăng nhập bằng google nên bỏ vì mình chưa xử lý được phần đấy đâu. Quan trọng là phần validate các trường dữ liệu khi code back end ý

**Comment by TranNgocBich99** [comment]
mình thấy giao diện đky, đăng nhập vậy là oke rồi, cuối tuần mình sẽ làm và commit cho các bạn xem nhé
