### ISSUE TITLE
Thống nhất code Back-end viết theo mô hình MVC

### ISSUE THREAD

**Issue by TranNgocBich99** [TranNgocBich99/TBH-HOTEL#9]

**Comment by TrangMai288** [comment]
Mình nghĩ code theo mô hình MVC sẽ khá dễ để phân công mỗi người với mỗi chức năng tương ứng và MVC bọn mình cũng đã được tìm hiểu và được thực hành qua môn Lập trình hướng đối tượng nên sẽ quen thuộc hơn

**Comment by TranNgocBich99** [comment]
> Mình nghĩ code theo mô hình MVC sẽ khá dễ để phân công mỗi người với mỗi chức năng tương ứng và MVC bọn mình cũng đã được tìm hiểu và được thực hành qua môn Lập trình hướng đối tượng nên sẽ quen thuộc hơn

Mình cũng nghĩ như thế, code MVC là phổ biến, rất tiện lợi và chuyên nghiệp nữa, phù hợp cho việc quản lý code và chia việc các kiểu....

**Comment by TrangMai288** [comment]
Bạn Hạnh Trang và bạn Huệ thấy sao?

**Comment by nguyenthihue269** [comment]
t đồng ý với ý kiến của hai bạn

**Comment by trangvu9905** [comment]
Theo mình thì viết theo mô hình MVC:
MVC cho thấy sự chuyên nghiệp trong lập trình và phân tích đối tượng, vì được chia các thành phần riêng biệt nên hoạt động độc lập tách biệt giúp phát triển ứng dụng nhanh hơn, đơn giản hơn và dễ nâng cấp, bảo trì hơn.

**Comment by trangvu9905** [comment]
> Bạn Hạnh Trang và bạn Huệ thấy sao?

Theo mình thì chúng ta viết theo mô hình MVC
